shogi/config/routes.rb
Rails.application.routes.draw do

  post 'users/login'      => 'users#login'
  post 'users/logout'     => 'users#logout'
  get  'plays/:id/state'  => 'plays#state'
  get  'plays/:id/users'  => 'plays#users'
  get  'plays/:id'        => 'plays#show'
  get  'plays/:id/winner' => 'plays#get_winner'
  get  'plays/:id/pieces' => 'plays#get_pieces'
  get  'plays/:id/test' => 'plays#test'
  get  'plays/:id/rooms' => 'plays#room'
  post 'plays/update'     => 'plays#update'

  get 'plays/end/:id' => 'plays#end'

end

shogi/app/models/play.rb
class Play < ActiveRecord::Base
  has_many :user, :as => :turn_player
  has_many :user, :as => :first_player
  has_many :user, :as => :last_player
  has_many :user, :as => :winner
  validates :room_no, presence: true
  validates :state, presence: true

  def end?
    self.state == "finish" || self.state == "exit"
  end

  def end(id)
    self.state = "finish"
    save
  end
end

shogi/app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:state, :users, :get_winner, :show, :get_pieces]

  def state
    render "state", :formats => [:json], :handlers => [:jbuilder]
  end

  def users
    render "users", :formats => [:json], :handlers => [:jbuilder]
  end

  def show
    # 現在のターン数、観客の人数、状態を返す
    @watcher_count = PlayingUser.where( :play => @play, :role => 'watcher' ).count
    render "show", :formats => [:json], :handlers => [:jbuilder]
  end

  def get_winner
    render "winner", :formats => [:json], :handlers => [:jbuilder]
  end

  def get_pieces
    @pieces = Piece.where( :play => @play.id ).all
    # binding.pry
    render "pieces", :formats => [:json], :hanlders => [:jbuilder]
  end

  # 駒情報の更新
  def update
    # begin
      # 1. play_idとuser_idとmove_idでpiecesテーブルからデータを拾ってくる
      @p_move = Piece.where( :play_id => params[:play_id], :piece_id => params[:move_id] ).first
      # 2. posxとposyを更新
      @p_move.posx = params[:posx]
      @p_move.posy = params[:posy]
      # binding.pry
      @p_move.promote = (params[:promote] == "True")? true : false
      @p_move.save!

      # render :json => @p_move
      @play = Play.find(params[:play_id])

      # binding.pry
      # 3. get_idが-1かどうか確認
      if params[:get_id] != "-1"
        # 4. get_idが-1でない場合、play_idとget_idでpiecesテーブルからデータを拾ってくる
        if params[:get_id] != ""
          @p_get = Piece.where( :play_id => params[:play_id], :piece_id => params[:get_id] ).first
          # 5. posxとposyを更新して保存
          @p_get.posx = 0
          @p_get.posy = 0
          @p_get.promote = false
          @p_get.owner = params[:user_id]
          @p_get.save!
          # 6. get_idが39or40なら終了処理
          if params[:get_id] == "40" || params[:get_id] == "39"
            @play.winner = @play.turn_player
            @play.state = "finish"
            # 7. ルーム内全員を退出処理
            @users = PlayingUser.where( :play_id => params[:play_id] ).all
            @users.each do |user|
              user.exit_flag = true
              user.save!
            end
          end
        end
      end
      # 8. ターン数を増やす
      @play.turn_count += 1
      if @play.turn_player == @play.first_player 
        @play.turn_player = @play.last_player 
      else
        @play.turn_player = @play.first_player
      end
      @play.save!
      # レスポンスは成功したかしてないか
    @pieces = Piece.where( :play => @play.id ).all
    render "pieces", :formats => [:json], :hanlders => [:jbuilder]
    # rescue
    #   @error = "error!"
    #   render "user/error", :formats => [:json], :handlers => [:jbuilder]
    # end
  end

  # debug用
  def end
    @play = Play.find(params[:id])
    render 'state', :formats => [:json], :hanlders => [:jbuilder]
  end

  def test
    @test = 'hoge'
    render 'test', :formats => [:json], :hanlders => [:jbuilder]
  end

  def room
    @active = Play.where(state: 'playing').select(:id, :state, :room_no, :first_player, :last_player)
    @active += Play.where(state: 'waiting').select(:id, :state, :room_no, :first_player, :last_player)
    @active.sort! {|a, b| a[:room_no].to_i <=> b[:room_no].to_i}
    render 'room', :formats => [:json], :hanlders => [:jbuilder]
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_play
      begin
        @play = Play.find(params[:id])
      rescue
        @error = "record not found"
        render "users/error", :formats => [:json], :handlers => [:jbuilder] and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def play_params
      params.require(:play).permit(:turn_player, :turn_number, :end_flag, :room_no)
    end
end

shogi/app/helpers/plays_helper.rb
module PlaysHelper
end

shogi/app/views/plays/_form.html.erb
<%= form_for(@play) do |f| %>
  <% if @play.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@play.errors.count, "error") %> prohibited this play from being saved:</h2>

      <ul>
      <% @play.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :turn_player %><br>
    <%= f.number_field :turn_player %>
  </div>
  <div class="field">
    <%= f.label :turn_number %><br>
    <%= f.number_field :turn_number %>
  </div>
  <div class="field">
    <%= f.label :end_flag %><br>
    <%= f.text_field :end_flag %>
  </div>
  <div class="field">
    <%= f.label :room_no %><br>
    <%= f.number_field :room_no %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shogi/app/views/plays/edit.html.erb
<h1>Editing play</h1>

<%= render 'form' %>

<%= link_to 'Show', @play %> |
<%= link_to 'Back', plays_path %>

shogi/app/views/plays/index.html.erb
<h1>Listing plays</h1>

<table>
  <thead>
    <tr>
      <th>Turn player</th>
      <th>Turn number</th>
      <th>End flag</th>
      <th>Room no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plays.each do |play| %>
      <tr>
        <td><%= play.turn_player %></td>
        <td><%= play.turn_number %></td>
        <td><%= play.end_flag %></td>
        <td><%= play.room_no %></td>
        <td><%= link_to 'Show', play %></td>
        <td><%= link_to 'Edit', edit_play_path(play) %></td>
        <td><%= link_to 'Destroy', play, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Play', new_play_path %>

shogi/app/views/plays/new.html.erb
<h1>New play</h1>

<%= render 'form' %>

<%= link_to 'Back', plays_path %>

shogi/app/views/plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Turn player:</strong>
  <%= @play.turn_player %>
</p>

<p>
  <strong>Turn number:</strong>
  <%= @play.turn_number %>
</p>

<p>
  <strong>End flag:</strong>
  <%= @play.end_flag %>
</p>

<p>
  <strong>Room no:</strong>
  <%= @play.room_no %>
</p>

<%= link_to 'Edit', edit_play_path(@play) %> |
<%= link_to 'Back', plays_path %>